version: '3.7'

services:
  app:
      image: 'docker-spring-boot-global-tran:latest'
      build: .
      container_name: global-tran
      depends_on:
        - db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/main_db
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=12345
      ports:
        - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345